import { KeyboardColours } from "./Types";

export const keyboardColoursInit: KeyboardColours = {
  Q: "white",
  W: "white",
  E: "white",
  R: "white",
  T: "white",
  Y: "white",
  U: "white",
  I: "white",
  O: "white",
  P: "white",
  A: "white",
  S: "white",
  D: "white",
  F: "white",
  G: "white",
  H: "white",
  J: "white",
  K: "white",
  L: "white",
  Z: "white",
  X: "white",
  C: "white",
  V: "white",
  B: "white",
  N: "white",
  M: "white",
};
